# Generated by Django 5.0.7 on 2025-04-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serie', '0002_serie_anneeacademique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='name',
            field=models.CharField(default=4, max_length=20),
            preserve_default=False,
        ),
    ]
