# Generated by Django 5.0.7 on 2025-04-22 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serie', '0003_alter_serie_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serie',
            name='anneeacademique',
        ),
    ]
