# Generated by Django 5.0.7 on 2025-04-22 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anneeacademique', '0004_anneecademique_status_cloture'),
        ('serie', '0004_remove_serie_anneeacademique'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='anneeacademique',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='anneeacademique.anneecademique'),
            preserve_default=False,
        ),
    ]
