# Generated by Django 5.0.7 on 2025-05-10 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etablissement', '0003_etablissement_abreviation'),
        ('serie', '0005_serie_anneeacademique'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='etablissement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='etablissement.etablissement'),
            preserve_default=False,
        ),
    ]
