# Generated by Django 5.0.7 on 2024-12-15 01:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anneeacademique', '0002_remove_anneecademique_libelle_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Renumeration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('Janvier', 'Janvier'), ('Février', 'Février'), ('Mars', 'Mars'), ('Avril', 'Avril'), ('Mai', 'Mai'), ('Juin', 'Juin'), ('Juillet', 'Juillet'), ('Août', 'Août'), ('Septembre', 'Septembre'), ('Octobre', 'Octobre'), ('Novembre', 'Novembre'), ('Décembre', 'Décembre')], max_length=20, null=True)),
                ('amount', models.CharField(max_length=300, null=True)),
                ('indeminte', models.CharField(max_length=1000, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('anneeacademique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anneeacademique.anneecademique')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personnel_à_renumerer', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renumeration_enregistrées_par', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
