# Generated by Django 5.0.7 on 2025-03-23 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renumeration', '0003_alter_renumeration_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='type_contrat',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Enseignant', 'Enseignant')], max_length=20, null=True),
        ),
    ]
