# Generated by Django 5.0.7 on 2025-03-23 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anneeacademique', '0003_anneecademique_end_date_anneecademique_start_date'),
        ('renumeration', '0004_contrat_type_contrat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='renumerationadmin',
            name='contrat',
        ),
        migrations.RemoveField(
            model_name='renumerationadmin',
            name='date',
        ),
        migrations.AddField(
            model_name='renumerationadmin',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='renumerationadmin',
            name='anneeacademique',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='anneeacademique.anneecademique'),
        ),
        migrations.AddField(
            model_name='renumerationadmin',
            name='date_renumeration',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='renumerationadmin',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='renumerationadmins', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
