# Generated by Django 5.0.7 on 2025-03-23 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renumeration', '0005_remove_renumerationadmin_contrat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='renumerationadmin',
            old_name='indeminte',
            new_name='indemnite',
        ),
    ]
