# Generated by Django 5.0.7 on 2025-04-04 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renumeration', '0006_rename_indeminte_renumerationadmin_indemnite'),
    ]

    operations = [
        migrations.AddField(
            model_name='renumeration',
            name='status',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='renumerationadmin',
            name='status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
