# Generated by Django 5.0.7 on 2025-04-11 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renumeration', '0007_renumeration_status_renumerationadmin_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='poste',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
