# Generated by Django 5.0.7 on 2025-05-29 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renumeration', '0010_renumeration_mode_payment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='renumeration',
            old_name='indeminte',
            new_name='indemnite',
        ),
        migrations.RemoveField(
            model_name='renumeration',
            name='personnel',
        ),
        migrations.AddField(
            model_name='renumeration',
            name='responsable',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, related_name='renumeration_enregistrées_par', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='renumeration',
            name='type_renumerartion',
            field=models.CharField(choices=[('Administrateur scolaire', 'Administrateur scolaire'), ('Enseignant du fondamental', 'Enseignant du fondamental'), ('Enseignant du secondaire', 'Enseignant du secondaire')], default='Administrateur scolaire', max_length=40),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='type_contrat',
            field=models.CharField(choices=[('Administrateur scolaire', 'Administrateur scolaire'), ('Enseignant du fondamental', 'Enseignant du fondamental'), ('Enseignant du secondaire', 'Enseignant du secondaire')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='renumeration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renumerations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='RenumerationAdmin',
        ),
    ]
