# Generated by Django 5.0.7 on 2025-05-29 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renumeration', '0011_rename_indeminte_renumeration_indemnite_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='renumeration',
            old_name='type_renumerartion',
            new_name='type_renumeration',
        ),
    ]
