# Generated by Django 5.0.7 on 2025-06-22 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renumeration', '0012_rename_type_renumerartion_renumeration_type_renumeration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrat',
            name='type_contrat',
            field=models.CharField(choices=[('Administrateur scolaire', 'Administrateur scolaire'), ('Enseignant du cycle fondamental', 'Enseignant du cycle fondamental'), ('Enseignant du cycle secondaire', 'Enseignant du cycle secondaire')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='renumeration',
            name='type_renumeration',
            field=models.CharField(choices=[('Administrateur scolaire', 'Administrateur scolaire'), ('Enseignant du cycle fondamental', 'Enseignant du cycle fondamental'), ('Enseignant du cycle secondaire', 'Enseignant du cycle secondaire')], default='Administrateur scolaire', max_length=40),
        ),
    ]
