# Generated by Django 5.0.7 on 2025-05-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etablissement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etablissement',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default='2025-05-07'),
            preserve_default=False,
        ),
    ]
