# Generated by Django 5.0.7 on 2025-05-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etablissement', '0002_etablissement_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='etablissement',
            name='abreviation',
            field=models.CharField(default='school', max_length=100),
            preserve_default=False,
        ),
    ]
