# Generated by Django 5.0.7 on 2025-06-02 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('etablissement', '0005_etablissementuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='etablissementuser',
            name='group',
            field=models.ForeignKey(default=16, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
            preserve_default=False,
        ),
    ]
