# Generated by Django 5.0.7 on 2025-06-02 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etablissement', '0006_etablissementuser_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EtablissementUser',
        ),
    ]
