# Generated by Django 5.0.7 on 2025-04-22 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classe', '0002_classe_anneeacademique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classe',
            name='anneeacademique',
        ),
    ]
