# Generated by Django 5.0.7 on 2025-05-05 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classe', '0004_classe_anneeacademique'),
        ('cycle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='cycle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cycle.cycle'),
            preserve_default=False,
        ),
    ]
