# Generated by Django 5.0.7 on 2025-05-05 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classe', '0005_classe_cycle'),
        ('cycle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='cycle.cycle'),
        ),
    ]
