# Generated by Django 5.0.7 on 2025-05-10 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classe', '0006_alter_classe_cycle'),
        ('etablissement', '0003_etablissement_abreviation'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='etablissement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='etablissement.etablissement'),
            preserve_default=False,
        ),
    ]
