# Generated by Django 5.0.7 on 2025-05-10 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classe', '0007_classe_etablissement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classe',
            name='etablissement',
        ),
    ]
