# Generated by Django 5.0.7 on 2024-11-05 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appname', models.CharField(max_length=100)),
                ('appeditor', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('version', models.CharField(max_length=10, null=True)),
                ('devise', models.CharField(max_length=10, null=True)),
                ('theme', models.CharField(choices=[('primary', 'primary'), ('info', 'info'), ('success', 'success'), ('danger', 'danger'), ('secondary', 'secondary'), ('dark', 'dark')], max_length=200, null=True)),
                ('text_color', models.CharField(max_length=20, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='media')),
                ('width_logo', models.CharField(max_length=3, null=True)),
                ('height_logo', models.TextField(max_length=3, null=True)),
            ],
        ),
    ]
