# Generated by Django 5.0.7 on 2024-11-07 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='text_color',
            field=models.CharField(choices=[('text-primary', 'text-primary'), ('text-info', 'text-info'), ('text-success', 'text-success'), ('text-danger', 'text-danger'), ('text-secondary', 'text-secondary'), ('text-dark', 'text-dark'), ('text-light', 'text-light')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='theme',
            field=models.CharField(choices=[('bg-primary', 'bg-primary'), ('bg-info', 'bg-info'), ('bg-success', 'bg-success'), ('bg-danger', 'bg-danger'), ('bg-secondary', 'bg-secondary'), ('bg-dark', 'bg-dark')], max_length=200, null=True),
        ),
    ]
