# Generated by Django 5.0.7 on 2025-03-30 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anneeacademique', '0003_anneecademique_end_date_anneecademique_start_date'),
        ('school', '0002_alter_setting_text_color_alter_setting_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='anneeacademique',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='anneeacademique.anneecademique'),
        ),
    ]
