# Generated by Django 5.0.7 on 2025-04-11 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_setting_anneeacademique'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='email',
            field=models.TextField(null=True),
        ),
    ]
