# Generated by Django 5.0.7 on 2025-05-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_settingsupuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsupuser',
            name='email',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='settingsupuser',
            name='height_logo',
            field=models.CharField(default='brunelebata2@gmail.com', max_length=3),
            preserve_default=False,
        ),
    ]
