# Generated by Django 5.0.7 on 2025-03-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depense', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='depense',
            name='signe',
            field=models.CharField(choices=[('Entrée', 'Entrée'), ('Sortie', 'Sortie')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='depense',
            name='type_depense',
            field=models.CharField(choices=[('Frais du loyé', 'Frais du loyé'), ("Frais de l'électricité", "Frais de l'électricité"), ("Frais de l'internet", "Frais de l'internet"), ('Frais du téléphone', 'Frais du téléphone'), ('Autre', 'Autre')], max_length=200, null=True),
        ),
    ]
