# Generated by Django 5.0.7 on 2025-03-27 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depense', '0002_depense_signe_alter_depense_type_depense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depense',
            name='type_depense',
            field=models.CharField(choices=[('Frais du loyé', 'Frais du loyé'), ("Frais de l'électricité", "Frais de l'électricité"), ("Frais de l'internet", "Frais de l'internet"), ('Frais du téléphone', 'Frais du téléphone'), ('Travaux', 'Travaux'), ('Don', 'Don'), ('Autre', 'Autre')], max_length=200, null=True),
        ),
    ]
