# Generated by Django 5.0.7 on 2025-04-18 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depense', '0004_historicaldepense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depense',
            name='type_depense',
            field=models.CharField(choices=[('Frais du loyer', 'Frais du loyer'), ("Frais de l'électricité", "Frais de l'électricité"), ("Frais de l'internet", "Frais de l'internet"), ('Frais du téléphone', 'Frais du téléphone'), ('Travaux', 'Travaux'), ('Don', 'Don'), ('Autre', 'Autre')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldepense',
            name='type_depense',
            field=models.CharField(choices=[('Frais du loyer', 'Frais du loyer'), ("Frais de l'électricité", "Frais de l'électricité"), ("Frais de l'internet", "Frais de l'internet"), ('Frais du téléphone', 'Frais du téléphone'), ('Travaux', 'Travaux'), ('Don', 'Don'), ('Autre', 'Autre')], max_length=200, null=True),
        ),
    ]
