# Generated by Django 5.0.7 on 2025-06-26 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emploi_temps', '0001_initial'),
        ('matiere', '0006_remove_matiere_etablissement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emploitemps',
            name='matiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='matiere.matiere'),
        ),
    ]
