# Generated by Django 5.0.7 on 2025-05-05 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycle',
            name='libelle',
            field=models.CharField(choices=[('Prescolaire', 'Prescolaire'), ('Primaire', 'Primaire'), ('Collège', 'Collège'), ('Lycée', 'Lycée')], max_length=100, null=True),
        ),
    ]
