# Generated by Django 5.0.7 on 2025-05-07 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle', '0002_alter_cycle_libelle'),
        ('etablissement', '0002_etablissement_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='etablissement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to='etablissement.etablissement'),
            preserve_default=False,
        ),
    ]
