# Generated by Django 5.0.7 on 2024-11-23 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_auth', '0002_alter_student_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=500)),
                ('datecontact', models.DateTimeField(auto_now_add=True)),
                ('reading_status', models.IntegerField(default=0, null=True)),
                ('deletion_status', models.IntegerField(default=0, null=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_auth.parent')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_auth.student')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
