# Generated by Django 5.0.7 on 2024-11-23 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anneeacademique', '0002_remove_anneecademique_libelle_and_more'),
        ('contact', '0002_remove_contact_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='anneeacademique',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='anneeacademique.anneecademique'),
        ),
    ]
