# Generated by Django 5.0.7 on 2025-04-04 03:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_contact_anneeacademique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='deletion_status',
            new_name='delete_status',
        ),
        migrations.AddField(
            model_name='contact',
            name='sending_stutus',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
