# Generated by Django 5.0.7 on 2025-04-04 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_rename_deletion_status_contact_delete_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(choices=[('Réclamation de notes', 'Réclamation de notes'), ('Harcèlement', 'Harcèlement')], max_length=100, null=True),
        ),
    ]
