# Generated by Django 5.0.7 on 2025-04-04 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_alter_contact_parent_alter_contact_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(choices=[('Réclamation de notes', 'Réclamation de notes'), ('Harcèlement', 'Harcèlement'), ('Paiement des frais', 'Paiement des frais')], max_length=100, null=True),
        ),
    ]
