# Generated by Django 5.0.7 on 2025-04-04 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_alter_contact_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='sending_stutus',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
