# Generated by Django 5.0.7 on 2025-04-05 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0009_rename_sending_stutus_contact_sending_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='status_admin',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='status_customer',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
