# Generated by Django 5.0.7 on 2025-04-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0010_contact_status_admin_contact_status_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='status_admin',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='status_customer',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
