# Generated by Django 5.0.7 on 2025-04-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0011_alter_contact_status_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='status_admin',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='status_customer',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
