# Generated by Django 5.0.7 on 2025-04-18 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anneeacademique', '0003_anneecademique_end_date_anneecademique_start_date'),
        ('contact', '0012_alter_contact_status_admin_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='status_admin',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='status_customer',
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('datemessage', models.DateTimeField(auto_now_add=True)),
                ('reading_status', models.IntegerField(default=0, null=True)),
                ('delete_status', models.IntegerField(default=0, null=True)),
                ('anneeacademique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anneeacademique.anneecademique')),
                ('beneficiaire', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='benefinicaire', to=settings.AUTH_USER_MODEL)),
                ('expediteur', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='expediteur', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
