# Generated by Django 5.0.7 on 2025-07-08 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0014_alter_message_beneficiaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(choices=[('Réclamation de notes', 'Réclamation de notes'), ('Harcèlement', 'Harcèlement'), ('Frais de scolarité', 'Frais de scolarité'), ('Autre', 'Autre')], max_length=100, null=True),
        ),
    ]
