# Generated by Django 5.0.7 on 2024-11-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='date_absence',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
