# Generated by Django 5.0.7 on 2024-11-29 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0002_alter_absence_date_absence'),
        ('app_auth', '0002_alter_student_photo'),
        ('emargement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absencestudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_absence', models.DateField(auto_now_add=True, null=True)),
                ('motif', models.CharField(max_length=200, null=True)),
                ('emargement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emargement.emargement')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_auth.student')),
            ],
        ),
    ]
