# Generated by Django 5.0.7 on 2024-11-29 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0003_absencestudent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absencestudent',
            name='motif',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
