# Generated by Django 5.0.7 on 2024-11-30 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0004_alter_absencestudent_motif'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absencestudent',
            name='date_absence',
        ),
        migrations.AlterField(
            model_name='absencestudent',
            name='motif',
            field=models.CharField(default='', max_length=300, null=True),
        ),
    ]
