# Generated by Django 5.0.7 on 2025-04-03 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0007_absenceadmin_anneeacademique_alter_absenceadmin_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='absencestudent',
            name='status',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='absencestudent',
            name='status_parent',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
