# Generated by Django 5.0.7 on 2025-04-04 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0008_absencestudent_status_absencestudent_status_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='status',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='absenceadmin',
            name='status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
