# Generated by Django 5.0.7 on 2025-04-05 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0009_absence_status_absenceadmin_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absencestudent',
            name='status_parent',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
