# Generated by Django 5.0.7 on 2025-06-22 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0010_alter_absencestudent_status_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absencestudent',
            name='status_parent',
            field=models.IntegerField(default=0),
        ),
    ]
