# Generated by Django 5.0.7 on 2025-06-26 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0011_alter_absencestudent_status_parent'),
        ('matiere', '0006_remove_matiere_etablissement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='matiere',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='matiere.matiere'),
        ),
    ]
