# Generated by Django 5.0.7 on 2025-06-27 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0012_alter_absence_matiere'),
        ('matiere', '0006_remove_matiere_etablissement'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='status_decision',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='absenceadmin',
            name='status_decision',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='absencestudent',
            name='status_decision',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='absence',
            name='matiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='matiere.matiere'),
        ),
    ]
