# Generated by Django 5.0.7 on 2025-06-30 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0013_absence_status_decision_absenceadmin_status_decision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='date_limite',
            field=models.DateTimeField(auto_now_add=True, default='2025-06-03'),
            preserve_default=False,
        ),
    ]
