# Generated by Django 5.0.7 on 2025-07-01 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0015_alter_absence_date_limite'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='date_enregistrement',
            field=models.DateTimeField(auto_now_add=True, default='2025-06-30 00:00:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='absence',
            name='motif',
            field=models.CharField(default='', max_length=300, null=True),
        ),
    ]
