# Generated by Django 5.0.7 on 2025-07-03 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0016_absence_date_enregistrement_alter_absence_motif'),
    ]

    operations = [
        migrations.AddField(
            model_name='absenceadmin',
            name='date_enregistrement',
            field=models.DateTimeField(auto_now_add=True, default='2025-07-6 00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='absenceadmin',
            name='date_limite',
            field=models.DateTimeField(blank=True, default='2025-07-06 00:00:00'),
            preserve_default=False,
        ),
    ]
