# Generated by Django 5.0.7 on 2025-07-05 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0017_absenceadmin_date_enregistrement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absencestudent',
            name='motif',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
