# Generated by Django 5.0.7 on 2025-07-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0018_alter_absencestudent_motif'),
    ]

    operations = [
        migrations.AddField(
            model_name='absencestudent',
            name='date_enregistrement',
            field=models.DateTimeField(auto_now_add=True, default='2025-07-05 00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='absencestudent',
            name='date_limite',
            field=models.DateTimeField(blank=True, default='2025-07-05 00:00:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='absence',
            name='motif',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='absenceadmin',
            name='motif',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='absencestudent',
            name='motif',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
