# Generated by Django 5.0.7 on 2024-11-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anneeacademique', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anneecademique',
            name='libelle',
        ),
        migrations.AddField(
            model_name='anneecademique',
            name='annee_debut',
            field=models.IntegerField(default=2000, null=True),
        ),
        migrations.AddField(
            model_name='anneecademique',
            name='annee_fin',
            field=models.IntegerField(default=2001, null=True),
        ),
        migrations.AddField(
            model_name='anneecademique',
            name='separateur',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
