# Generated by Django 5.0.7 on 2024-12-21 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anneeacademique', '0002_remove_anneecademique_libelle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anneecademique',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='anneecademique',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
