# Generated by Django 5.0.7 on 2025-04-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anneeacademique', '0003_anneecademique_end_date_anneecademique_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='anneecademique',
            name='status_cloture',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
