# Generated by Django 5.0.7 on 2025-05-07 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anneeacademique', '0004_anneecademique_status_cloture'),
        ('etablissement', '0002_etablissement_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='anneecademique',
            name='etablissement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='anneeacademiques', to='etablissement.etablissement'),
            preserve_default=False,
        ),
    ]
