# Generated by Django 5.0.7 on 2025-05-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anneeacademique', '0005_anneecademique_etablissement'),
    ]

    operations = [
        migrations.AddField(
            model_name='anneecademique',
            name='status_access',
            field=models.BooleanField(default=True),
        ),
    ]
