# Generated by Django 5.0.7 on 2025-05-08 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anneeacademique', '0006_anneecademique_status_access'),
        ('etablissement', '0002_etablissement_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anneecademique',
            name='etablissement',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anneeacademiques', to='etablissement.etablissement'),
        ),
    ]
