# Generated by Django 5.0.7 on 2025-05-27 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anneeacademique', '0007_alter_anneecademique_etablissement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anneecademique',
            name='status_cloture',
            field=models.BooleanField(default=True),
        ),
    ]
