# Generated by Django 5.0.7 on 2025-05-05 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle', '0002_alter_cycle_libelle'),
        ('matiere', '0003_matiere_anneeacademique'),
    ]

    operations = [
        migrations.AddField(
            model_name='matiere',
            name='cycle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='matieres', to='cycle.cycle'),
            preserve_default=False,
        ),
    ]
