# Generated by Django 5.0.7 on 2024-11-11 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anneeacademique', '0002_remove_anneecademique_libelle_and_more'),
        ('app_auth', '0002_alter_student_photo'),
        ('salle', '0002_alter_salle_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateins', models.DateTimeField(auto_now_add=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=10.0, max_digits=10, null=True)),
                ('anneeacademique', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='anneeacademique.anneecademique')),
                ('salle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='salle.salle')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_auth.student')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
