# Generated by Django 5.0.7 on 2025-04-12 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='mode_paiement',
            field=models.CharField(choices=[('Espèce', 'Espèce'), ('Virement', 'Virement'), ('Mobile', 'Mobile')], default='Espèce', max_length=50, null=True),
        ),
    ]
