# Generated by Django 5.0.7 on 2025-05-08 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etablissement', '0002_etablissement_date'),
        ('inscription', '0002_inscription_mode_paiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='etablissement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='etablissement.etablissement'),
            preserve_default=False,
        ),
    ]
