# Generated by Django 5.0.7 on 2025-05-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0003_inscription_etablissement'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='status_access',
            field=models.BooleanField(default=True),
        ),
    ]
