# Generated by Django 5.0.7 on 2025-05-24 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0004_inscription_status_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='status_block',
            field=models.BooleanField(default=True),
        ),
    ]
