# Generated by Django 5.0.7 on 2025-05-25 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0005_inscription_status_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='date_block',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
