# Generated by Django 5.0.7 on 2025-05-25 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0006_inscription_date_block'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscription',
            name='date_block',
        ),
    ]
