# Generated by Django 5.0.7 on 2025-06-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0009_alter_inscription_responsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
