"""
Django settings for scolarite project.

Generated by 'django-admin startproject' using Django 4.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
#====== Code Twiolo : 4G55TJEDPSQ3MUXZFLLKE7RG
import os
import environ
from pathlib import Path
from django.contrib import messages

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-p#cd66wp!w^nsrj1)b*i=)io+3tpo8k%#s1#^^3qvda%f)=%ge'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'scolarite',
    'school',
    'app_auth',
    'anneeacademique',
    'matiere',
    'classe',
    'serie',
    'salle',
    'inscription',
    'programme',
    'enseignement',
    'composition',
    'emploi_temps',
    'absence',
    'publication',
    'activity',
    'paiement',
    'contact',
    'emargement',
    'cours',
    'renumeration',
    'calendrier',
    'depense',
    'cycle',
    'etablissement',
    'simple_history'
]

MAINTENANCE_MODE = False

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
    
    # Notre middleware
    'scolarite.middlewares.maintenance_middleware.MaintenanceMiddleware',  # Chemin vers le middleware
]

ROOT_URLCONF = 'scolarite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'scolarite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'school/static'),
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')
MEDIA_URL = '/media/'


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
#EMAIL_USE_SSL = False
EMAIL_PORT = 587
EMAIL_HOST_USER = 'eajccv@gmail.com'
EMAIL_HOST_PASSWORD = 'htpnbplhezawdpnb'


TWILIO_ACCOUNT_SID = 'ACe659c68ec0c22ec83acfedbcdd167218'
TWILIO_AUTH_TOKEN = 'a97e9361a4d92ab0e2357f66dce20a9b'
TWILIO_PHONE_NUMBER = '+19162325821'

# Initialiser l'instance d'environ
env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Recuperer les clés primaire et secondaire de Momo
MTN_PRIMARY_KEY = env("MTN_PRIMARY_KEY")
MTN_SECONDARY_KEY = env("MTN_SECONDARY_KEY")
MTN_API_URL = env("MTN_API_URL")

MESSAGE_TAGS = {
    messages.DEBUG: 'alert-warning',
    messages.INFO: 'alert-info',
    messages.SUCCESS: 'alert-success',
    messages.ERROR: 'alert-danger',
}

FERNET_KEY = "UQvdJZXcBijVleBm6T46daoUrCPQ2iiUBiLlYHuvVb0="

LANGUAGE_CODE = 'fr'