# Generated by Django 5.0.7 on 2025-04-03 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0004_autorisationpaymentsalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
