# Generated by Django 5.0.7 on 2025-04-03 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0005_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='status_parentr',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
