# Generated by Django 5.0.7 on 2025-04-04 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0006_payment_status_parentr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='status_parentr',
            new_name='status_parent',
        ),
    ]
