# Generated by Django 5.0.7 on 2025-04-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0007_rename_status_parentr_payment_status_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='mode_paiement',
            field=models.CharField(choices=[('Espèce', 'Espèce'), ('Virement', 'Virement'), ('Mobile', 'Mobile')], default='Espèce', max_length=50, null=True),
        ),
    ]
