# Generated by Django 5.0.7 on 2025-05-13 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etablissement', '0003_etablissement_abreviation'),
        ('paiement', '0011_autorisationpaymentetablissement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentetablissement',
            name='etablissement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c', to='etablissement.etablissement'),
        ),
    ]
