# Generated by Django 5.0.7 on 2025-05-31 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0013_alter_paymentetablissement_etablissement'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentetablissement',
            name='transaction_id',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
