# Generated by Django 5.0.7 on 2025-05-31 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0014_paymentetablissement_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentetablissement',
            name='date_payment',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
