# Generated by Django 5.0.7 on 2025-06-07 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0015_alter_paymentetablissement_date_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratetablissement',
            name='end_date',
            field=models.DateField(default='2024-02-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contratetablissement',
            name='start_date',
            field=models.DateField(default='2025-07-30'),
            preserve_default=False,
        ),
    ]
