# Generated by Django 5.0.7 on 2024-12-21 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anneeacademique', '0002_remove_anneecademique_libelle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvenementScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('anneeacademique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anneeacademique.anneecademique')),
            ],
        ),
        migrations.CreateModel(
            name='Trimestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('anneeacademique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anneeacademique.anneecademique')),
            ],
        ),
        migrations.CreateModel(
            name='Calendrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anneeacademique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anneeacademique.anneecademique')),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenement', to='calendrier.evenementscolaire')),
                ('trimestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trimestre', to='calendrier.trimestre')),
            ],
        ),
    ]
