# Generated by Django 5.0.7 on 2025-03-14 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendrier', '0002_alter_calendrier_evenement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendrier',
            name='evenement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendriers', to='calendrier.evenementscolaire'),
        ),
        migrations.AlterField(
            model_name='calendrier',
            name='trimestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendriers', to='calendrier.trimestre'),
        ),
    ]
