# Generated by Django 5.0.7 on 2025-04-16 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendrier', '0003_alter_calendrier_evenement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evenementscolaire',
            name='anneeacademique',
        ),
        migrations.AddField(
            model_name='evenementscolaire',
            name='trimestre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evenementscolaires', to='calendrier.trimestre'),
        ),
        migrations.DeleteModel(
            name='Calendrier',
        ),
    ]
