# Generated by Django 5.0.7 on 2025-04-23 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendrier', '0004_remove_evenementscolaire_anneeacademique_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenementscolaire',
            name='description',
            field=models.TextField(blank=True, default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evenementscolaire',
            name='trimestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenementscolaires', to='calendrier.trimestre'),
        ),
    ]
