# Generated by Django 5.0.7 on 2025-05-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendrier', '0005_alter_evenementscolaire_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trimestre',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
