from django.db import models
from django.contrib.auth.models import User, Group
from etablissement.models import Etablissement

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    datenais = models.DateField(null=True)
    phone = models.CharField(max_length=100, null=True)
    address = models.TextField(null=True)
    profession = models.CharField(max_length=50, null=True)
    diplome = models.CharField(max_length=50, null=True)
    photo = models.ImageField(upload_to="media", null=True, blank=True)
    SEX = [
        ('Masculin','Masculin'),
        ('Feminin','Feminin')
    ]
    gender = models.CharField(max_length=100, null=True, choices=SEX)
    LIST_COUNTRY=[
        ('Afrique du Sud','Afrique du Sud'),
        ('Afghanistan','Afghanistan'),
        ('Albanie','Albanie'),
        ('Algérie','Algérie'),
        ('Allemagne','Allemagne'),
        ('Andorre','Andorre'),
        ('Angola','Angola'),
        ('Antigua-et-Barbuda','Antigua-et-Barbuda'),
        ('Arabie Saoudite','Arabie Saoudite'),
        ('Argentine','Argentine'),
        ('Arménie','Arménie'),
        ('Australie','Australie'),
        ('Autriche','Autriche'),
        ('Azerbaïdjan','Azerbaïdjan'),
        ('Bahamas','Bahamas'),
        ('Bahreïn','Bahreïn'),
        ('Bangladesh','Bangladesh'),
        ('Barbade','Barbade'),
        ('Belgique','Belgique'),
        ('Belize','Belize'),
        ('Bénin','Bénin'),
        ('Bhoutan','Bhoutan'),
        ('Biélorussie','Biélorussie'),
        ('Birmanie','Birmanie'),
        ('Bolivie','Bolivie'),
        ('Bosnie-Herzégovine','Bosnie-Herzégovine'),
        ('Botswana','Botswana'),
        ('Brésil','Brésil'),
        ('Brunei','Brunei'),
        ('Bulgarie','Bulgarie'),
        ('Burkina Faso','Burkina Faso'),
        ('Burundi','Burundi'),
        ('Cambodge','Cambodge'),
        ('Cameroun','Cameroun'),
        ('Canada','Canada'),
        ('Cap-Vert','Cap-Vert'),
        ('Chili','Chili'),
        ('Chine','Chine'),
        ('Chypre','Chypre'),
        ('Colombie','Colmobie'),
        ('Comores','Comores'),
        ('Congo-Brazzaville','Congo-Brazzaville'),
        ('Corée du Nord','Corée du Nord'),
        ('Corée du Sud','Corée du Sud'),
        ('Costa Rica','Costa Rica'),
        ('Côte d’Ivoire','Côte d’Ivoire'),
        ('Croatie','Croatie'),
        ('Cuba','Cuba'),
        ('Danemark','Danemark'),
        ('Djibouti','Djibouti'),
        ('Dominique','Dominique'),
        ('Égypte','Égypte'),
        ('Émirats arabes unis','Émirats arabes unis'),
        ('Équateur','Équateur'),
        ('Érythrée','Érythrée'),
        ('Espagne','Espagne'),
        ('Eswatini','Eswatini'),
        ('Estonie','Estonie'),
        ('États-Unis','États-Unis'),
        ('Éthiopie','Éthiopie'),
        ('Fidji','Fidji'),
        ('Finlande','Finlande'),
        ('France','France'),
        ('Gabon','Gabon'),
        ('Gambie','Gambie'),
        ('Géorgie','Géorgie'),
        ('Ghana','Ghana'),
        ('Grèce','Grèce'),
        ('Grenade','Grenade'),
        ('Guatemala','Guatemala'),
        ('Guinée','Guinée'),
        ('Guinée équatoriale','Guinée équatoriale'),
        ('Guinée-Bissau','Guinée-Bissau'),
        ('Guyana','Guyana'),
        ('Haïti','Haïti'),
        ('Honduras','Honduras'),
        ('Hongrie','Hongrie'),
        ('Îles Cook','Îles Cook'),
        ('Îles Marshall','Îles Marshall'),
        ('Inde','Inde'),
        ('Indonésie','Indonésie'),
        ('Irak','Irak'),
        ('Iran','Iran'),
        ('Irlande','Irlande'),
        ('Islande','Islande'),
        ('Israël','Israël'),
        ('Italie','Italie'),
        ('Jamaïque','Jamaïque'),
        ('Japon','Japon'),
        ('Jordanie','Jordanie'),
        ('Kazakhstan','Kazakhstan'),
        ('Kenya','Kenya'),
        ('Kirghizistan','Kirghizistan'),
        ('Kiribati','Kiribati'),
        ('Koweït','Koweït'),
        ('Laos','Laos'),
        ('Lesotho','Lesotho'),
        ('Lettonie','Lettonie'),
        ('Liban','Liban'),
        ('Liberia','Liberia'),
        ('Libye','Libye'),
        ('Liechtenstein','Liechtenstein'),
        ('Lituanie','Lituanie'),
        ('Luxembourg','Luxembourg'),
        ('Macédoine','Macédoine'),
        ('Madagascar','Madagascar'),
        ('Malaisie','Malaisie'),
        ('Malawi','Malawi'),
        ('Maldives','Maldives'),
        ('Mali','Mali'),
        ('Malte','Malte'),
        ('Maroc','Maroc'),
        ('Maurice','Maurice'),
        ('Mauritanie','Mauritanie'),
        ('Mexique','Mexique'),
        ('Micronésie','Micronésie'),
        ('Moldavie','Moldavie'),
        ('Monaco','Monaco'),
        ('Mongolie','Mongolie'),
        ('Monténégro','Monténégro'),
        ('Mozambique','Mozambique'),
        ('Namibie','Namibie'),
        ('Nauru','Nauru'),
        ('Népal','Katmandou'),
        ('Nicaragua','Nicaragua'),
        ('Niger','Niger'),
        ('Nigeria','Nigeria'),
        ('Niue','Niue'),
        ('Norvège','Norvège'),
        ('Nouvelle-Zélande','Nouvelle-Zélande'),
        ('Oman','Oman'),
        ('Ouganda','Ouganda'),
        ('Ouzbékistan','Ouzbékistan'),
        ('Pakistan','Pakistan'),
        ('Palaos','Palaos'),
        ('Palestine','Palestine'),
        ('Panama','Panama'),
        ('Papouasie-Nouvelle-Guinée','Papouasie-Nouvelle-Guinée'),
        ('Paraguay','Paraguay'),
        ('Pays-Bas','Pays-Bas'),
        ('Pérou','Pérou'),
        ('Philippines','Philippines'),
        ('Pologne','Pologne'),
        ('Portugal','Portugal'),
        ('Qatar','Qatar'),
        ('République centrafricaine','République centrafricaine'),
        ('République démocratique du Congo','République démocratique du Congo'),
        ('République Dominicaine','République Dominicaine'),
        ('République tchèque','République tchèque'),
        ('Roumanie','Roumanie'),
        ('Royaume-Uni','Royaume-Uni'),
        ('Russie','Russie'),
        ('Rwanda','Rwanda'),
        ('Saint-Kitts-et-Nevis','Saint-Kitts-et-Nevis'),
        ('Saint-Vincent-et-les-Grenadines','Saint-Vincent-et-les-Grenadines'),
        ('Sainte-Lucie','Sainte-Lucie'),
        ('Saint-Marin','Saint-Marin'),
        ('Salomon','Salomon'),
        ('Salvador','Salvador'),
        ('Samoa','Samoa'),
        ('São Tomé-et-Principe','São Tomé-et-Principe'),
        ('Sénégal','Sénégal'),
        ('Serbie','Serbie'),
        ('Seychelles','Seychelles'),
        ('Sierra Leone','Sierra Leone'),
        ('Singapour','Singapour'),
        ('Slovaquie','Slovaquie'),
        ('Slovénie','Slovénie'),
        ('Somalie','Somalie'),
        ('Soudan','Soudan'),
        ('Soudan du Sud','Soudan du Sud'),
        ('Sri Lanka','Sri Lanka'),
        ('Suède','Suède'),
        ('Suisse','Suisse'),
        ('Suriname','Suriname'),
        ('Syrie','Syrie'),
        ('Tadjikistan','Tadjikistan'),
        ('Tanzanie','Tanzanie'),
        ('Tchad','Tchad'),
        ('Thaïlande','Thaïlande'),
        ('Timor oriental','Timor oriental'),
        ('Togo','Togo'),
        ('Tonga','Tonga'),
        ('Trinité-et-Tobago','Trinité-et-Tobago'),
        ('Tunisie','Tunisie'),
        ('Turkménistan','Turkménistan'),
        ('Turquie','Turquie'),
        ('Tuvalu','Tuvalu'),
        ('Ukraine','Ukraine'),
        ('Uruguay','Uruguay'),
        ('Vanuatu','Vanuatu'),
        ('Vatican','Vatican'),
        ('Venezuela','Venezuela'),
        ('Viêt Nam','Viêt Nam'),
        ('Yémen','Yémen'),
        ('Zambie','Zambie'),
        ('Zimbabwe','Zimbabwe')
    ]
    country = models.CharField(max_length=100, null=True, choices=LIST_COUNTRY)
    
class EtablissementUser(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    group = models.ForeignKey(Group, on_delete=models.CASCADE)
    etablissement = models.ForeignKey(Etablissement, on_delete=models.CASCADE)
 
    class Meta:
        unique_together = ('user', 'group', 'etablissement')  # Évite les doublons

    def __str__(self):
        return f"{self.user.username} - {self.group.name} - {self.etablissement.name}"

class Parent(models.Model):
    etablissement = models.ForeignKey(Etablissement, on_delete=models.CASCADE, null=True, default=None, related_name="parents")
    username=models.CharField(max_length=50, null=True)
    firstname=models.CharField(max_length=100, null=True)
    lastname=models.CharField(max_length=100, null=True) 
    address=models.TextField()
    phone=models.CharField(max_length=50, null=True)
    profession=models.CharField(max_length=100, null=True)
    SEX=[
        ('Masculin','Masculin'),
        ('Feminin','Feminin')
    ]
    gender=models.CharField(max_length=100, null=True, choices=SEX)
    LIST_COUNTRY=[
        ('Afrique du Sud','Afrique du Sud'),
        ('Afghanistan','Afghanistan'),
        ('Albanie','Albanie'),
        ('Algérie','Algérie'),
        ('Allemagne','Allemagne'),
        ('Andorre','Andorre'),
        ('Angola','Angola'),
        ('Antigua-et-Barbuda','Antigua-et-Barbuda'),
        ('Arabie Saoudite','Arabie Saoudite'),
        ('Argentine','Argentine'),
        ('Arménie','Arménie'),
        ('Australie','Australie'),
        ('Autriche','Autriche'),
        ('Azerbaïdjan','Azerbaïdjan'),
        ('Bahamas','Bahamas'),
        ('Bahreïn','Bahreïn'),
        ('Bangladesh','Bangladesh'),
        ('Barbade','Barbade'),
        ('Belgique','Belgique'),
        ('Belize','Belize'),
        ('Bénin','Bénin'),
        ('Bhoutan','Bhoutan'),
        ('Biélorussie','Biélorussie'),
        ('Birmanie','Birmanie'),
        ('Bolivie','Bolivie'),
        ('Bosnie-Herzégovine','Bosnie-Herzégovine'),
        ('Botswana','Botswana'),
        ('Brésil','Brésil'),
        ('Brunei','Brunei'),
        ('Bulgarie','Bulgarie'),
        ('Burkina Faso','Burkina Faso'),
        ('Burundi','Burundi'),
        ('Cambodge','Cambodge'),
        ('Cameroun','Cameroun'),
        ('Canada','Canada'),
        ('Cap-Vert','Cap-Vert'),
        ('Chili','Chili'),
        ('Chine','Chine'),
        ('Chypre','Chypre'),
        ('Colombie','Colmobie'),
        ('Comores','Comores'),
        ('Congo-Brazzaville','Congo-Brazzaville'),
        ('Corée du Nord','Corée du Nord'),
        ('Corée du Sud','Corée du Sud'),
        ('Costa Rica','Costa Rica'),
        ('Côte d’Ivoire','Côte d’Ivoire'),
        ('Croatie','Croatie'),
        ('Cuba','Cuba'),
        ('Danemark','Danemark'),
        ('Djibouti','Djibouti'),
        ('Dominique','Dominique'),
        ('Égypte','Égypte'),
        ('Émirats arabes unis','Émirats arabes unis'),
        ('Équateur','Équateur'),
        ('Érythrée','Érythrée'),
        ('Espagne','Espagne'),
        ('Eswatini','Eswatini'),
        ('Estonie','Estonie'),
        ('États-Unis','États-Unis'),
        ('Éthiopie','Éthiopie'),
        ('Fidji','Fidji'),
        ('Finlande','Finlande'),
        ('France','France'),
        ('Gabon','Gabon'),
        ('Gambie','Gambie'),
        ('Géorgie','Géorgie'),
        ('Ghana','Ghana'),
        ('Grèce','Grèce'),
        ('Grenade','Grenade'),
        ('Guatemala','Guatemala'),
        ('Guinée','Guinée'),
        ('Guinée équatoriale','Guinée équatoriale'),
        ('Guinée-Bissau','Guinée-Bissau'),
        ('Guyana','Guyana'),
        ('Haïti','Haïti'),
        ('Honduras','Honduras'),
        ('Hongrie','Hongrie'),
        ('Îles Cook','Îles Cook'),
        ('Îles Marshall','Îles Marshall'),
        ('Inde','Inde'),
        ('Indonésie','Indonésie'),
        ('Irak','Irak'),
        ('Iran','Iran'),
        ('Irlande','Irlande'),
        ('Islande','Islande'),
        ('Israël','Israël'),
        ('Italie','Italie'),
        ('Jamaïque','Jamaïque'),
        ('Japon','Japon'),
        ('Jordanie','Jordanie'),
        ('Kazakhstan','Kazakhstan'),
        ('Kenya','Kenya'),
        ('Kirghizistan','Kirghizistan'),
        ('Kiribati','Kiribati'),
        ('Koweït','Koweït'),
        ('Laos','Laos'),
        ('Lesotho','Lesotho'),
        ('Lettonie','Lettonie'),
        ('Liban','Liban'),
        ('Liberia','Liberia'),
        ('Libye','Libye'),
        ('Liechtenstein','Liechtenstein'),
        ('Lituanie','Lituanie'),
        ('Luxembourg','Luxembourg'),
        ('Macédoine','Macédoine'),
        ('Madagascar','Madagascar'),
        ('Malaisie','Malaisie'),
        ('Malawi','Malawi'),
        ('Maldives','Maldives'),
        ('Mali','Mali'),
        ('Malte','Malte'),
        ('Maroc','Maroc'),
        ('Maurice','Maurice'),
        ('Mauritanie','Mauritanie'),
        ('Mexique','Mexique'),
        ('Micronésie','Micronésie'),
        ('Moldavie','Moldavie'),
        ('Monaco','Monaco'),
        ('Mongolie','Mongolie'),
        ('Monténégro','Monténégro'),
        ('Mozambique','Mozambique'),
        ('Namibie','Namibie'),
        ('Nauru','Nauru'),
        ('Népal','Katmandou'),
        ('Nicaragua','Nicaragua'),
        ('Niger','Niger'),
        ('Nigeria','Nigeria'),
        ('Niue','Niue'),
        ('Norvège','Norvège'),
        ('Nouvelle-Zélande','Nouvelle-Zélande'),
        ('Oman','Oman'),
        ('Ouganda','Ouganda'),
        ('Ouzbékistan','Ouzbékistan'),
        ('Pakistan','Pakistan'),
        ('Palaos','Palaos'),
        ('Palestine','Palestine'),
        ('Panama','Panama'),
        ('Papouasie-Nouvelle-Guinée','Papouasie-Nouvelle-Guinée'),
        ('Paraguay','Paraguay'),
        ('Pays-Bas','Pays-Bas'),
        ('Pérou','Pérou'),
        ('Philippines','Philippines'),
        ('Pologne','Pologne'),
        ('Portugal','Portugal'),
        ('Qatar','Qatar'),
        ('République centrafricaine','République centrafricaine'),
        ('République démocratique du Congo','République démocratique du Congo'),
        ('République Dominicaine','République Dominicaine'),
        ('République tchèque','République tchèque'),
        ('Roumanie','Roumanie'),
        ('Royaume-Uni','Royaume-Uni'),
        ('Russie','Russie'),
        ('Rwanda','Rwanda'),
        ('Saint-Kitts-et-Nevis','Saint-Kitts-et-Nevis'),
        ('Saint-Vincent-et-les-Grenadines','Saint-Vincent-et-les-Grenadines'),
        ('Sainte-Lucie','Sainte-Lucie'),
        ('Saint-Marin','Saint-Marin'),
        ('Salomon','Salomon'),
        ('Salvador','Salvador'),
        ('Samoa','Samoa'),
        ('São Tomé-et-Principe','São Tomé-et-Principe'),
        ('Sénégal','Sénégal'),
        ('Serbie','Serbie'),
        ('Seychelles','Seychelles'),
        ('Sierra Leone','Sierra Leone'),
        ('Singapour','Singapour'),
        ('Slovaquie','Slovaquie'),
        ('Slovénie','Slovénie'),
        ('Somalie','Somalie'),
        ('Soudan','Soudan'),
        ('Soudan du Sud','Soudan du Sud'),
        ('Sri Lanka','Sri Lanka'),
        ('Suède','Suède'),
        ('Suisse','Suisse'),
        ('Suriname','Suriname'),
        ('Syrie','Syrie'),
        ('Tadjikistan','Tadjikistan'),
        ('Tanzanie','Tanzanie'),
        ('Tchad','Tchad'),
        ('Thaïlande','Thaïlande'),
        ('Timor oriental','Timor oriental'),
        ('Togo','Togo'),
        ('Tonga','Tonga'),
        ('Trinité-et-Tobago','Trinité-et-Tobago'),
        ('Tunisie','Tunisie'),
        ('Turkménistan','Turkménistan'),
        ('Turquie','Turquie'),
        ('Tuvalu','Tuvalu'),
        ('Ukraine','Ukraine'),
        ('Uruguay','Uruguay'),
        ('Vanuatu','Vanuatu'),
        ('Vatican','Vatican'),
        ('Venezuela','Venezuela'),
        ('Viêt Nam','Viêt Nam'),
        ('Yémen','Yémen'),
        ('Zambie','Zambie'),
        ('Zimbabwe','Zimbabwe')
    ]
    country = models.CharField(max_length=100, null=True, choices=LIST_COUNTRY)
    password = models.CharField(max_length=50, null=True)
    status_access = models.BooleanField(default=True, null=False)

class Student(models.Model):
    etablissement = models.ForeignKey(Etablissement, on_delete=models.CASCADE, null=False, related_name="students")
    parent = models.ForeignKey(Parent, on_delete=models.CASCADE, null=True)
    username = models.CharField(max_length=50, null=True)
    firstname = models.CharField(max_length=100, null=True)
    lastname = models.CharField(max_length=100, null=True) 
    datenais = models.DateField(null=True)
    lieunais = models.CharField(max_length=100, null=False) 
    address = models.TextField()
    SEX = [
        ('Masculin','Masculin'),
        ('Feminin','Feminin')
    ]
    gender = models.CharField(max_length=100, null=True, choices=SEX)
    LIST_COUNTRY = [
        ('Afrique du Sud','Afrique du Sud'),
        ('Afghanistan','Afghanistan'),
        ('Albanie','Albanie'),
        ('Algérie','Algérie'),
        ('Allemagne','Allemagne'),
        ('Andorre','Andorre'),
        ('Angola','Angola'),
        ('Antigua-et-Barbuda','Antigua-et-Barbuda'),
        ('Arabie Saoudite','Arabie Saoudite'),
        ('Argentine','Argentine'),
        ('Arménie','Arménie'),
        ('Australie','Australie'),
        ('Autriche','Autriche'),
        ('Azerbaïdjan','Azerbaïdjan'),
        ('Bahamas','Bahamas'),
        ('Bahreïn','Bahreïn'),
        ('Bangladesh','Bangladesh'),
        ('Barbade','Barbade'),
        ('Belgique','Belgique'),
        ('Belize','Belize'),
        ('Bénin','Bénin'),
        ('Bhoutan','Bhoutan'),
        ('Biélorussie','Biélorussie'),
        ('Birmanie','Birmanie'),
        ('Bolivie','Bolivie'),
        ('Bosnie-Herzégovine','Bosnie-Herzégovine'),
        ('Botswana','Botswana'),
        ('Brésil','Brésil'),
        ('Brunei','Brunei'),
        ('Bulgarie','Bulgarie'),
        ('Burkina Faso','Burkina Faso'),
        ('Burundi','Burundi'),
        ('Cambodge','Cambodge'),
        ('Cameroun','Cameroun'),
        ('Canada','Canada'),
        ('Cap-Vert','Cap-Vert'),
        ('Chili','Chili'),
        ('Chine','Chine'),
        ('Chypre','Chypre'),
        ('Colombie','Colmobie'),
        ('Comores','Comores'),
        ('Congo-Brazzaville','Congo-Brazzaville'),
        ('Corée du Nord','Corée du Nord'),
        ('Corée du Sud','Corée du Sud'),
        ('Costa Rica','Costa Rica'),
        ('Côte d’Ivoire','Côte d’Ivoire'),
        ('Croatie','Croatie'),
        ('Cuba','Cuba'),
        ('Danemark','Danemark'),
        ('Djibouti','Djibouti'),
        ('Dominique','Dominique'),
        ('Égypte','Égypte'),
        ('Émirats arabes unis','Émirats arabes unis'),
        ('Équateur','Équateur'),
        ('Érythrée','Érythrée'),
        ('Espagne','Espagne'),
        ('Eswatini','Eswatini'),
        ('Estonie','Estonie'),
        ('États-Unis','États-Unis'),
        ('Éthiopie','Éthiopie'),
        ('Fidji','Fidji'),
        ('Finlande','Finlande'),
        ('France','France'),
        ('Gabon','Gabon'),
        ('Gambie','Gambie'),
        ('Géorgie','Géorgie'),
        ('Ghana','Ghana'),
        ('Grèce','Grèce'),
        ('Grenade','Grenade'),
        ('Guatemala','Guatemala'),
        ('Guinée','Guinée'),
        ('Guinée équatoriale','Guinée équatoriale'),
        ('Guinée-Bissau','Guinée-Bissau'),
        ('Guyana','Guyana'),
        ('Haïti','Haïti'),
        ('Honduras','Honduras'),
        ('Hongrie','Hongrie'),
        ('Îles Cook','Îles Cook'),
        ('Îles Marshall','Îles Marshall'),
        ('Inde','Inde'),
        ('Indonésie','Indonésie'),
        ('Irak','Irak'),
        ('Iran','Iran'),
        ('Irlande','Irlande'),
        ('Islande','Islande'),
        ('Israël','Israël'),
        ('Italie','Italie'),
        ('Jamaïque','Jamaïque'),
        ('Japon','Japon'),
        ('Jordanie','Jordanie'),
        ('Kazakhstan','Kazakhstan'),
        ('Kenya','Kenya'),
        ('Kirghizistan','Kirghizistan'),
        ('Kiribati','Kiribati'),
        ('Koweït','Koweït'),
        ('Laos','Laos'),
        ('Lesotho','Lesotho'),
        ('Lettonie','Lettonie'),
        ('Liban','Liban'),
        ('Liberia','Liberia'),
        ('Libye','Libye'),
        ('Liechtenstein','Liechtenstein'),
        ('Lituanie','Lituanie'),
        ('Luxembourg','Luxembourg'),
        ('Macédoine','Macédoine'),
        ('Madagascar','Madagascar'),
        ('Malaisie','Malaisie'),
        ('Malawi','Malawi'),
        ('Maldives','Maldives'),
        ('Mali','Mali'),
        ('Malte','Malte'),
        ('Maroc','Maroc'),
        ('Maurice','Maurice'),
        ('Mauritanie','Mauritanie'),
        ('Mexique','Mexique'),
        ('Micronésie','Micronésie'),
        ('Moldavie','Moldavie'),
        ('Monaco','Monaco'),
        ('Mongolie','Mongolie'),
        ('Monténégro','Monténégro'),
        ('Mozambique','Mozambique'),
        ('Namibie','Namibie'),
        ('Nauru','Nauru'),
        ('Népal','Katmandou'),
        ('Nicaragua','Nicaragua'),
        ('Niger','Niger'),
        ('Nigeria','Nigeria'),
        ('Niue','Niue'),
        ('Norvège','Norvège'),
        ('Nouvelle-Zélande','Nouvelle-Zélande'),
        ('Oman','Oman'),
        ('Ouganda','Ouganda'),
        ('Ouzbékistan','Ouzbékistan'),
        ('Pakistan','Pakistan'),
        ('Palaos','Palaos'),
        ('Palestine','Palestine'),
        ('Panama','Panama'),
        ('Papouasie-Nouvelle-Guinée','Papouasie-Nouvelle-Guinée'),
        ('Paraguay','Paraguay'),
        ('Pays-Bas','Pays-Bas'),
        ('Pérou','Pérou'),
        ('Philippines','Philippines'),
        ('Pologne','Pologne'),
        ('Portugal','Portugal'),
        ('Qatar','Qatar'),
        ('République centrafricaine','République centrafricaine'),
        ('République démocratique du Congo','République démocratique du Congo'),
        ('République Dominicaine','République Dominicaine'),
        ('République tchèque','République tchèque'),
        ('Roumanie','Roumanie'),
        ('Royaume-Uni','Royaume-Uni'),
        ('Russie','Russie'),
        ('Rwanda','Rwanda'),
        ('Saint-Kitts-et-Nevis','Saint-Kitts-et-Nevis'),
        ('Saint-Vincent-et-les-Grenadines','Saint-Vincent-et-les-Grenadines'),
        ('Sainte-Lucie','Sainte-Lucie'),
        ('Saint-Marin','Saint-Marin'),
        ('Salomon','Salomon'),
        ('Salvador','Salvador'),
        ('Samoa','Samoa'),
        ('São Tomé-et-Principe','São Tomé-et-Principe'),
        ('Sénégal','Sénégal'),
        ('Serbie','Serbie'),
        ('Seychelles','Seychelles'),
        ('Sierra Leone','Sierra Leone'),
        ('Singapour','Singapour'),
        ('Slovaquie','Slovaquie'),
        ('Slovénie','Slovénie'),
        ('Somalie','Somalie'),
        ('Soudan','Soudan'),
        ('Soudan du Sud','Soudan du Sud'),
        ('Sri Lanka','Sri Lanka'),
        ('Suède','Suède'),
        ('Suisse','Suisse'),
        ('Suriname','Suriname'),
        ('Syrie','Syrie'),
        ('Tadjikistan','Tadjikistan'),
        ('Tanzanie','Tanzanie'),
        ('Tchad','Tchad'),
        ('Thaïlande','Thaïlande'),
        ('Timor oriental','Timor oriental'),
        ('Togo','Togo'),
        ('Tonga','Tonga'),
        ('Trinité-et-Tobago','Trinité-et-Tobago'),
        ('Tunisie','Tunisie'),
        ('Turkménistan','Turkménistan'),
        ('Turquie','Turquie'),
        ('Tuvalu','Tuvalu'),
        ('Ukraine','Ukraine'),
        ('Uruguay','Uruguay'),
        ('Vanuatu','Vanuatu'),
        ('Vatican','Vatican'),
        ('Venezuela','Venezuela'),
        ('Viêt Nam','Viêt Nam'),
        ('Yémen','Yémen'),
        ('Zambie','Zambie'),
        ('Zimbabwe','Zimbabwe')
    ]
    country = models.CharField(max_length=100, null=True, choices=LIST_COUNTRY)
    password = models.CharField(max_length=50, null=True)
    
    def __str__(self):
        return self.lastname+" "+self.firstname