# Generated by Django 5.0.7 on 2024-11-24 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anneeacademique', '0002_remove_anneecademique_libelle_and_more'),
        ('matiere', '0002_matiere_text_color_matiere_theme'),
        ('salle', '0002_alter_salle_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Emargement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('Janvier', 'Janvier'), ('Février', 'Février'), ('Mars', 'Mars'), ('Avril', 'Avril'), ('Mai', 'Mai'), ('Juin', 'Juin'), ('Juillet', 'Juillet'), ('Août', 'Août'), ('Septembre', 'Septembre'), ('Octobre', 'Octobre'), ('Novembre', 'Novembre'), ('Décembre', 'Décembre')], max_length=20, null=True)),
                ('jour', models.CharField(choices=[('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi'), ('Samedi', 'Samedi'), ('Dimanche', 'Dimanche')], max_length=10, null=True)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('seance', models.CharField(choices=[('Cours', 'Cours'), ('Travail Dirigé', 'Travail Dirigé'), ('Contrôle', 'Contrôle'), ('Travail Pratique', 'Travail Pratique')], max_length=300, null=True)),
                ('titre', models.CharField(max_length=100, null=True)),
                ('date_emargement', models.DateField(auto_now_add=True)),
                ('anneeacademique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anneeacademique.anneecademique')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emargement_enseignant', to=settings.AUTH_USER_MODEL)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matiere.matiere')),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salle.salle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emargement_enregistrées_par', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
