# Generated by Django 5.0.7 on 2025-04-04 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emargement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emargement',
            name='status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
