# Generated by Django 5.0.7 on 2025-06-27 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emargement', '0002_emargement_status'),
        ('matiere', '0006_remove_matiere_etablissement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emargement',
            name='matiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='matiere.matiere'),
        ),
    ]
