# Generated by Django 5.0.7 on 2024-12-13 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('cours', '0002_alter_cours_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentCours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_object_id', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('reading_status', models.CharField(max_length=300, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('author_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cours.cours')),
            ],
        ),
    ]
