# Generated by Django 5.0.7 on 2025-06-01 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0003_commentcours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentcours',
            name='reading_status',
            field=models.IntegerField(default=0),
        ),
    ]
