# Generated by Django 5.0.7 on 2025-06-22 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anneeacademique', '0008_alter_anneecademique_status_cloture'),
        ('app_auth', '0012_student_lieunais'),
        ('cours', '0004_alter_commentcours_reading_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadCours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_status', models.IntegerField(default=0)),
                ('anneeacademique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anneeacademique.anneecademique')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cours.cours')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_auth.student')),
            ],
        ),
    ]
