# Generated by Django 5.0.7 on 2024-11-11 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anneeacademique', '0002_remove_anneecademique_libelle_and_more'),
        ('matiere', '0001_initial'),
        ('salle', '0002_alter_salle_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enseigner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volumehoraire', models.IntegerField(default=1)),
                ('cout_heure', models.DecimalField(decimal_places=2, default=10.0, max_digits=10, null=True)),
                ('anneeacademique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anneeacademique.anneecademique')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matiere.matiere')),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salle.salle')),
            ],
        ),
    ]
