# Generated by Django 5.0.7 on 2024-11-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enseignement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseigner',
            name='trimestre',
            field=models.CharField(choices=[('Trimestre 1', 'Trimestre 1'), ('Trimestre 2', 'Trimestre 2'), ('Trimestre 3', 'Trimestre 3')], max_length=20, null=True),
        ),
    ]
