# Generated by Django 5.0.7 on 2024-12-19 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0002_alter_student_photo'),
        ('enseignement', '0003_enseigner_date_eval_1_enseigner_date_eval_2_and_more'),
        ('matiere', '0002_matiere_text_color_matiere_theme'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationEnseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justification', models.CharField(max_length=20, null=True)),
                ('note', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('dateeval', models.DateTimeField(auto_now_add=True, null=True)),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matiere.matiere')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_auth.student')),
            ],
        ),
    ]
