# Generated by Django 5.0.7 on 2024-12-19 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anneeacademique', '0002_remove_anneecademique_libelle_and_more'),
        ('enseignement', '0004_evaluationenseignant'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationenseignant',
            name='anneeacademique',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='anneeacademique.anneecademique'),
        ),
    ]
