# Generated by Django 5.0.7 on 2024-11-12 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anneeacademique', '0002_remove_anneecademique_libelle_and_more'),
        ('app_auth', '0002_alter_student_photo'),
        ('matiere', '0001_initial'),
        ('salle', '0002_alter_salle_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Composer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation', models.CharField(max_length=20, null=True)),
                ('trimestre', models.CharField(max_length=20, null=True)),
                ('note', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('anneeacademique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anneeacademique.anneecademique')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matiere.matiere')),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salle.salle')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_auth.student')),
            ],
        ),
    ]
