# Generated by Django 5.0.7 on 2024-11-15 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composition', '0003_deliberation'),
    ]

    operations = [
        migrations.AddField(
            model_name='composer',
            name='numerocontrole',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
