# Generated by Django 5.0.7 on 2024-11-15 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composition', '0004_composer_numerocontrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composer',
            name='numerocontrole',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
