# Generated by Django 5.0.7 on 2025-04-03 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composition', '0005_alter_composer_numerocontrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='composer',
            name='status',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='composer',
            name='status_parent',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
