# Generated by Django 5.0.7 on 2025-04-05 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composition', '0006_composer_status_composer_status_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composer',
            name='status_parent',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
