# Generated by Django 5.0.7 on 2025-04-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composition', '0007_alter_composer_status_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliberation',
            name='status_cloture',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
