# Generated by Django 5.0.7 on 2025-04-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composition', '0008_deliberation_status_cloture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliberation',
            name='status_cloture',
        ),
        migrations.AddField(
            model_name='deliberation',
            name='date_cloture',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
