# Generated by Django 5.0.7 on 2025-04-20 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composition', '0009_remove_deliberation_status_cloture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliberation',
            name='status_cloture',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
