# Generated by Django 5.0.7 on 2025-04-22 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anneeacademique', '0004_anneecademique_status_cloture'),
        ('composition', '0010_deliberation_status_cloture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composer',
            name='anneeacademique',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compositions', to='anneeacademique.anneecademique'),
        ),
        migrations.AlterField(
            model_name='deliberation',
            name='anneeacademique',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliberations', to='anneeacademique.anneecademique'),
        ),
    ]
