# Generated by Django 5.0.7 on 2025-06-22 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composition', '0011_alter_composer_anneeacademique_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composer',
            name='status_parent',
            field=models.IntegerField(default=0),
        ),
    ]
