# Generated by Django 5.0.7 on 2025-04-22 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anneeacademique', '0004_anneecademique_status_cloture'),
        ('classe', '0002_classe_anneeacademique'),
        ('salle', '0002_alter_salle_price'),
        ('serie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salle',
            name='anneeacademique',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='anneeacademique.anneecademique'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salle',
            name='classe',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='classe.classe'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salle',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salle',
            name='serie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serie.serie'),
        ),
        migrations.AlterUniqueTogether(
            name='salle',
            unique_together={('anneeacademique', 'serie', 'classe', 'number')},
        ),
    ]
