# Generated by Django 5.0.7 on 2025-04-22 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salle', '0003_salle_anneeacademique_alter_salle_classe_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='salle',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='salle',
            name='anneeacademique',
        ),
    ]
