# Generated by Django 5.0.7 on 2025-05-05 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salle', '0005_salle_anneeacademique'),
        ('serie', '0005_serie_anneeacademique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salle',
            name='serie',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='serie.serie'),
        ),
    ]
