# Generated by Django 5.0.7 on 2025-05-06 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle', '0002_alter_cycle_libelle'),
        ('salle', '0006_alter_salle_serie'),
    ]

    operations = [
        migrations.AddField(
            model_name='salle',
            name='cycle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cycle.cycle'),
            preserve_default=False,
        ),
    ]
