# Generated by Django 5.0.7 on 2025-05-06 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle', '0002_alter_cycle_libelle'),
        ('salle', '0007_salle_cycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salle',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salles', to='cycle.cycle'),
        ),
    ]
