# Generated by Django 5.0.7 on 2025-05-23 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salle', '0010_remove_salle_etablissement'),
    ]

    operations = [
        migrations.AddField(
            model_name='salle',
            name='price_inscription',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
        ),
    ]
