# Generated by Django 5.0.7 on 2025-05-07 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0002_alter_student_photo'),
        ('etablissement', '0002_etablissement_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='etablissement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='etablissement.etablissement'),
            preserve_default=False,
        ),
    ]
