# Generated by Django 5.0.7 on 2025-05-09 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0003_student_etablissement'),
        ('etablissement', '0003_etablissement_abreviation'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='etablissement',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='etablissement.etablissement'),
        ),
    ]
