# Generated by Django 5.0.7 on 2025-05-10 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0005_alter_profile_address_alter_profile_phone'),
        ('etablissement', '0003_etablissement_abreviation'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='etablissement',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='etablissement.etablissement'),
        ),
    ]
