# Generated by Django 5.0.7 on 2025-05-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0006_parent_etablissement'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='status_access',
            field=models.BooleanField(default=True),
        ),
    ]
