# Generated by Django 5.0.7 on 2025-06-02 22:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0009_role'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('etablissement', '0007_delete_etablissementuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Role',
            new_name='EtablissementUser',
        ),
    ]
