# Generated by Django 5.0.7 on 2025-06-05 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0010_rename_role_etablissementuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='photo',
        ),
    ]
