# Generated by Django 5.0.7 on 2025-06-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0011_remove_student_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='lieunais',
            field=models.CharField(default='Paris', max_length=100),
            preserve_default=False,
        ),
    ]
